### ISSUE TITLE
Issue with nan Values in Actions

### ISSUE THREAD

**Issue by Zengxia-Guo** [jianda-chen/RAP_distance#3]
**Description**
During training, I encountered an issue where the actions contain nan values, causing the program to throw an AssertionError. Below is the detailed error log:
`| train | E: 4 | S: 1000 | D: 8.3 s | R: 8.6273 | BR: 0.0000 | ALOSS: 0.0000 | CLOSS: 0.0000 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
Action: [-0.08086713 -0.05156302  0.03296159 -0.20498772 -0.34121144  0.21736234]
Action Space: Box([-1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1.], (6,), float32)
Action: [nan nan nan nan nan nan]
Action Space: Box([-1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1.], (6,), float32)
Traceback (most recent call last):
  File "/workspace/RAP_distance/train.py", line 487, in <module>
    main()
  File "/workspace/RAP_distance/train.py", line 441, in main
    next_obs, reward, done, _ = env.step(action)
  File "/workspace/RAP_distance/utils.py", line 229, in step
    obs, reward, done, info = self.env.step(action)
  File "/opt/conda/lib/python3.10/site-packages/gym/wrappers/time_limit.py", line 18, in step
    observation, reward, done, info = self.env.step(action)
  File "/workspace/RAP_distance/dmc2gym/wrappers.py", line 172, in step
    assert self._norm_action_space.contains(action)
AssertionError
`

**Problem Description**
In the fourth episode of training, the generated action contains nan values, which causes the env.step(action) call to fail and raises an AssertionError. The specific action and action space information are as follows:

`Action Space: Box([-1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1.], (6,), float32)
Action: [-0.08086713 -0.05156302  0.03296159 -0.20498772 -0.34121144  0.21736234]
Action Space: Box([-1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1.], (6,), float32)
Action: [nan nan nan nan nan nan]
`

**Request for Help**
I would appreciate any advice or solutions to ensure that actions do not contain nan values during training.
Thank you for your assistance!

**Comment by jianda-chen** [comment]
The `nan` issue might be caused by the torch version. You can try older torch version, e.g. torch==1.7.1 .

**Comment by Amoliang** [comment]
您的来信我已收到，将尽快查看，谢谢！

**Comment by Amoliang** [comment]
Dear Jianda Chen,

I am writing to seek your advice regarding an issue I'm encountering while trying to install a specific version of torch to this problem. Below are the details of my environment:

**System Environment:**
`root@g01:/workspace/RAP_distance# nvidia-smi
Mon May 20 01:05:37 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     Off |   00000000:01:00.0 Off |                  Off |
|  0%   48C    P8             20W /  450W |      10MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090 Ti     Off |   00000000:05:00.0 Off |                  Off |
|  0%   46C    P8             15W /  450W |      75MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
`

`root@g01:/workspace/RAP_distance# python --version
Python 3.10.14
`
**Installed Packages:**
`Package                   Version
------------------------- ---------------
absl-py                   2.1.0
anaconda-anon-usage       0.4.4
archspec                  0.2.3
asttokens                 2.0.5
astunparse                1.6.3
attrs                     23.1.0
beautifulsoup4            4.12.2
boltons                   23.0.0
Brotli                    1.0.9
bypy                      1.8.5
certifi                   2024.2.2
cffi                      1.16.0
chardet                   4.0.0
charset-normalizer        2.0.4
click                     8.1.7
cloudpickle               3.0.0
conda                     23.5.2
conda-build               24.3.0
conda-content-trust       0.2.0
conda_index               0.4.0
conda-libmamba-solver     23.7.0
conda-package-handling    2.2.0
conda_package_streaming   0.9.0
contourpy                 1.2.1
cryptography              42.0.5
cycler                    0.12.1
Cython                    3.0.10
decorator                 5.1.1
dill                      0.3.8
distro                    1.8.0
dm_control                1.0.19
dm-env                    1.6
dm-tree                   0.1.8
dmc2gym                   1.0.0
dnspython                 2.6.1
dotmap                    1.3.30
etils                     1.7.0
exceptiongroup            1.2.0
executing                 0.8.3
expecttest                0.2.1
fasteners                 0.19
filelock                  3.13.1
fonttools                 4.51.0
fsspec                    2024.3.1
glfw                      2.7.0
gmpy2                     2.1.2
grpcio                    1.63.0
gym                       0.20.0
gym-notices               0.0.8
hypothesis                6.100.1
idna                      3.4
imageio                   2.34.1
imageio-ffmpeg            0.4.9
importlib_resources       6.4.0
ipython                   8.20.0
jedi                      0.18.1
Jinja2                    3.1.3
jsonpatch                 1.33
jsonpointer               2.1
jsonschema                4.19.2
jsonschema-specifications 2023.7.1
kiwisolver                1.4.5
kornia                    0.5.1
labmaze                   1.0.6
lark                      1.1.9
lazy_loader               0.4
libarchive-c              2.9
libmambapy                1.5.8
lxml                      5.2.2
Markdown                  3.6
MarkupSafe                2.1.3
matplotlib                3.9.0
matplotlib-inline         0.1.6
menuinst                  2.0.2
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
more-itertools            10.1.0
mpmath                    1.3.0
mujoco                    3.1.5
mujoco-py                 2.1.2.14
multiprocess              0.70.16
networkx                  3.1
numpy                     1.23.4
opencv-python             4.9.0.80
optree                    0.11.0
packaging                 23.2
parso                     0.8.3
pexpect                   4.8.0
pillow                    10.2.0
pip                       24.0
pkginfo                   1.9.6
platformdirs              3.10.0
pluggy                    1.0.0
prompt-toolkit            3.0.43
protobuf                  4.25.3
psutil                    5.9.0
ptyprocess                0.7.0
pure-eval                 0.2.2
pycosat                   0.6.6
pycparser                 2.21
pygame                    2.5.2
Pygments                  2.15.1
PyOpenGL                  3.1.7
pyOpenSSL                 24.0.0
pyparsing                 3.0.9
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-etcd               0.4.5
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.30.2
requests                  2.31.0
requests-toolbelt         1.0.0
rpds-py                   0.10.6
ruamel.yaml               0.17.21
ruamel.yaml.clib          0.2.6
scikit-image              0.23.2
scikit-video              1.1.11
scipy                     1.13.0
setuptools                65.5.0
six                       1.16.0
sortedcontainers          2.4.0
soupsieve                 2.5
stack-data                0.2.0
sympy                     1.12
tb-nightly                2.17.0a20240515
tensorboard-data-server   0.7.2
termcolor                 2.4.0
tifffile                  2024.5.10
tomli                     2.0.1
toolz                     0.12.0
torch                     1.11.0
torchaudio                2.3.0
torchelastic              0.2.2
torchvision               0.18.0
tqdm                      4.65.0
traitlets                 5.7.1
triton                    2.3.0
truststore                0.8.0
types-dataclasses         0.6.6
typing_extensions         4.11.0
urllib3                   2.1.0
wcwidth                   0.2.5
Werkzeug                  3.0.3
wheel                     0.38.4
youtube-dl                2021.12.17
zipp                      3.18.2
zstandard                 0.19.0
`

I attempted to install torch==1.7.1, torchvision==0.8.2, and torchaudio==0.7.2 using the following command:
`pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2
`
However, I encountered an error stating that there is no matching distribution found. It appears that torch 1.7.1 is not compatible with CUDA 12.4.

**Comment by Amoliang** [comment]
> The `nan` issue might be caused by the torch version. You can try older torch version, e.g. torch==1.7.1 .

  - torchaudio==0.7.2 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0']
  - torchvision==0.8.2 -> python[version='>=3.6,<3.7.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
cudatoolkit=11.0 -> libgcc-ng[version='>=7.3.0']
torchaudio==0.7.2 -> python[version='>=3.9,<3.10.0a0'] -> libgcc-ng[version='>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0']
torchvision==0.8.2 -> jpeg[version='<=9b'] -> libgcc-ng[version='>=11.2.0|>=7.2.0|>=7.5.0|>=8.4.0']
torchvision==0.8.2 -> libgcc-ng[version='>=7.3.0']
python=3.10 -> libgcc-ng[version='>=11.2.0|>=7.5.0']
python=3.10 -> bzip2[version='>=1.0.8,<2.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']

Package _openmp_mutex conflicts for:
torchvision==0.8.2 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']
python=3.10 -> libgcc-ng[version='>=11.2.0'] -> _openmp_mutex[version='>=4.5']
cudatoolkit=11.0 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']

Package pytorch conflicts for:
torchvision==0.8.2 -> pytorch[version='1.7.1|1.7.1.*']
torchaudio==0.7.2 -> pytorch==1.7.1

Package cudatoolkit conflicts for:
torchvision==0.8.2 -> cudatoolkit[version='>=10.1,<10.2|>=11.0,<11.1|>=10.2,<10.3|>=9.2,<9.3']
torchaudio==0.7.2 -> pytorch==1.7.1 -> cudatoolkit[version='>=10.1,<10.2|>=11.0,<11.1|>=10.2,<10.3|>=9.2,<9.3']

Package numpy conflicts for:
torchvision==0.8.2 -> numpy[version='>=1.11']
torchvision==0.8.2 -> pytorch==1.7.1 -> numpy[version='>=1.16.6,<2.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - python=3.10 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - torchvision==0.8.2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35


root@g01:/workspace/RAP_distance#

**Comment by Amoliang** [comment]
root@g01:/workspace/RAP_distance# ./run_local.sh
../log/cheetah_run_2024-05-20-01-33-03
Traceback (most recent call last):
  File "/workspace/RAP_distance/train.py", line 14, in <module>
    from logger import Logger
  File "/workspace/RAP_distance/logger.py", line 8, in <module>
    import torchvision
  File "/opt/conda/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/opt/conda/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'
root@g01:/workspace/RAP_distance#

**Comment by Zengxia-Guo** [comment]
Thank you. Based on your suggestion, I have resolved the issue of nan values by using Docker image pytorch/Pytorch: 1.7.1 cuda11.0 cudnn8 dev. But why is ALOSS negative here and what does it mean. (I recently read your paper and am currently researching experimental code. I have many areas that I do not understand and would like to ask for your advice.)

`| train | E: 26 | S: 6500 | D: 11.0 s | R: 9.3067 | BR: 0.0516 | ALOSS: -7.4499 | CLOSS: 0.0221 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 27 | S: 6750 | D: 10.9 s | R: 13.4442 | BR: 0.0527 | ALOSS: -7.7079 | CLOSS: 0.0254 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 28 | S: 7000 | D: 11.0 s | R: 18.2660 | BR: 0.0541 | ALOSS: -7.8978 | CLOSS: 0.0228 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 29 | S: 7250 | D: 11.0 s | R: 8.5523 | BR: 0.0517 | ALOSS: -8.1137 | CLOSS: 0.0231 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 30 | S: 7500 | D: 11.0 s | R: 12.6716 | BR: 0.0531 | ALOSS: -8.3132 | CLOSS: 0.0226 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| eval | S: 7500 | ER: 1.4013
| eval | S: 7500 | ER: 1.3304
| eval | S: 7500 | ER: 1.3962
| eval | S: 7500 | ER: 0.7532
| eval | S: 7500 | ER: 1.3104
| train | E: 31 | S: 7750 | D: 16.3 s | R: 14.2239 | BR: 0.0534 | ALOSS: -8.5087 | CLOSS: 0.0227 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 32 | S: 8000 | D: 11.0 s | R: 16.4379 | BR: 0.0516 | ALOSS: -8.6723 | CLOSS: 0.0247 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 33 | S: 8250 | D: 11.0 s | R: 11.4438 | BR: 0.0533 | ALOSS: -8.8470 | CLOSS: 0.0224 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 34 | S: 8500 | D: 11.0 s | R: 18.4024 | BR: 0.0534 | ALOSS: -9.0096 | CLOSS: 0.0263 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 35 | S: 8750 | D: 11.0 s | R: 18.2989 | BR: 0.0532 | ALOSS: -9.1825 | CLOSS: 0.0249 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 36 | S: 9000 | D: 10.9 s | R: 9.4131 | BR: 0.0529 | ALOSS: -9.2857 | CLOSS: 0.0220 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 37 | S: 9250 | D: 11.0 s | R: 9.5185 | BR: 0.0535 | ALOSS: -9.4056 | CLOSS: 0.0220 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 38 | S: 9500 | D: 11.0 s | R: 19.4781 | BR: 0.0536 | ALOSS: -9.5602 | CLOSS: 0.0235 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 39 | S: 9750 | D: 11.0 s | R: 8.8815 | BR: 0.0533 | ALOSS: -9.6693 | CLOSS: 0.0245 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| train | E: 40 | S: 10000 | D: 11.0 s | R: 18.4672 | BR: 0.0531 | ALOSS: -9.8003 | CLOSS: 0.0243 | RLOSS: 0.0000 | RHO: 0.0000 | MR: 0.0000 | EI: 0
| eval | S: 10000 | ER: 4.4221
| eval | S: 10000 | ER: 6.2904
| eval | S: 10000 | ER: 1.2938
| eval | S: 10000 | ER: 2.4657
| eval | S: 10000 | ER: 4.0768`

**Comment by jianda-chen** [comment]
The `ALOSS` is actor loss. Please refer to the SAC paper or the [code](https://github.com/jianda-chen/RAP_distance/blob/89f5f9adb5f05240bf7a9e1ae2cb6bb121f3730f/agent/baseline_agent.py#L228) for the definition of actor loss. It can be negative by definition.
